export const {
  PORT,
  MONGODB_URI,
  JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET,
  JWT_ACCESS_EXPIRATION_MINUTES,
  JWT_REFRESH_EXPIRATION_MINUTES,
  APP_URL,
  NODE_ENV,
  GOOGLE_CLIENT_ID,
} = process.env;
 